import {
  APPLICATION_DEFINITION_SCHEMA_V2,
  RESOURCE_DEFINITION_SCHEMA,
  defineApplication,
  defineResource,
  type CapabilityDefinition,
  type Contract,
} from '@victframework/sdk';
import { compileApplication } from '@victframework/application';
import type { ApplicationPlan } from '@victframework/application';

/**
 * YOUR APPLICATION DEFINITION — author-owned.
 *
 * This file (and src/lib/components/) is the ONLY application code you need
 * to write. Everything else generated by the scaffolder is the generic Vict
 * host: it renders whatever you declare here, resolves any route (including
 * parameters), loads every declared view, validates every declared action
 * input contract at the boundary, and dispatches capability actions through
 * the governed runtime. You never edit host files to change your domain.
 *
 * The starter 'items' domain below is a MINIMAL WORKING EXAMPLE: replace it
 * with your own resources, contracts, capabilities, views, forms, screens,
 * and actions. Custom Svelte components are code islands: create them under
 * src/lib/components/ and register them in src/lib/components/registry.ts.
 */

export const itemResource = defineResource({
  schema: RESOURCE_DEFINITION_SCHEMA,
  id: 'items',
  revision: '1',
  identity: { key: 'id' },
  fields: [
    { name: 'id', type: 'string', required: true, label: 'Id' },
    { name: 'title', type: 'string', required: true, label: 'Title' },
    { name: 'status', type: 'string', label: 'Status' },
  ],
  queries: { list: { sort: ['title'], pagination: true } },
  mutations: [
    { op: 'create', effect: 'write', idempotency: 'keyed', permissions: ['items.write'] },
    { op: 'update', effect: 'write', permissions: ['items.write'] },
  ],
  authorization: { effect: 'read' },
});

export const application = defineApplication({
  schema: APPLICATION_DEFINITION_SCHEMA_V2,
  id: 'app.starter',
  revision: '1',
  name: 'Build Check App',
  routes: [
    { id: 'home', path: '/', screenId: 's.dashboard', nav: { label: 'Dashboard', order: 1 } },
    { id: 'items', path: '/items', screenId: 's.items', nav: { label: 'Items', order: 2 } },
  ],
  screens: [
    {
      id: 's.dashboard',
      title: 'Build Check App',
      layout: [
        {
          name: 'main',
          surfaces: [
            { role: 'text', id: 't.welcome', content: 'Welcome to your Vict application.', level: 2 },
            {
              role: 'chart',
              id: 'c.status',
              viewId: 'v.items',
              kind: 'bar',
              xField: 'status',
              yField: 'qty',
              summary: 'Records per status',
              title: 'Records per status',
            },
          ],
        },
      ],
    },
    {
      id: 's.items',
      title: 'Items',
      breadcrumbs: [{ label: 'Home', routeId: 'home' }, { label: 'Items' }],
      layout: [
        {
          name: 'main',
          surfaces: [
            {
              role: 'table',
              id: 'tb.items',
              viewId: 'v.items',
              queryActionId: 'act.queryItems',
              searchFields: ['title'],
              pageSize: 10,
            },
          ],
        },
      ],
      states: {
        empty: { role: 'text', id: 't.empty', content: 'No items yet.' },
        denied: { role: 'text', id: 't.denied', content: 'Denied by the authorization boundary.' },
        failure: { role: 'text', id: 't.failure', content: 'Something failed safely.' },
      },
    },
  ],
  views: [
    {
      viewId: 'v.items',
      resourceId: 'items',
      resourceRevision: '1',
      fields: ['id', 'title', 'status'],
    },
  ],
  actions: [
    {
      kind: 'query',
      id: 'act.queryItems',
      revision: '1',
      resourceId: 'items',
      resourceRevision: '1',
    },
  ],
  resources: [{ resourceId: 'items', revision: '1' }],
  compatibility: { applicationSchema: APPLICATION_DEFINITION_SCHEMA_V2 },
});

/**
 * YOUR BINDINGS — author-owned.
 *
 * The generic application server consumes exactly these exports:
 * - resources:  resource definitions for the data adapter and its migrations;
 * - contracts:  Vict contracts referenced by actions/forms/mutations
 *               (boundary pre-validation + data-layer enforcement);
 * - capabilities: capability implementations invoked through the governed
 *               runtime for declared capability actions;
 * - capabilityEffects: per-action effect hooks persisting a governed run's
 *               validated output through the data adapter (fail-closed);
 * - grants:     the SERVER-SIDE authorization profile of this deployment
 *               (never sent to the UI; the UI cannot grant itself anything).
 */
export const resources = [itemResource];
export const contracts: readonly Contract<unknown>[] = [];
export const capabilities: readonly CapabilityDefinition<unknown, unknown>[] = [];
export const grants = ['items.read', 'items.write'];

/**
 * The author-owned capability-effect hook (the one declared extension seam
 * of the generic application server): after a capability action's governed
 * run completes with a validated output, this hook persists the effect
 * through the application-data adapter under the deployment's grants. A
 * failing hook is fail-closed: the action reports ACTION_FAILED and no
 * caller ever sees a success that was not persisted.
 */
export interface CapabilityEffect {
  readonly actionId: string;
  run(value: unknown, data: import('@victframework/application').ApplicationDataAdapter): Promise<void>;
}
export const capabilityEffects: readonly CapabilityEffect[] = [];

/** Compile the neutral definition into the immutable plan. */
export function compileAppPlan(): ApplicationPlan {
  const result = compileApplication({
    application,
    resources,
    // The compiler consumes identity entries only; the full contract and
    // capability objects bind to the runtime and the data adapter above.
    contracts: contracts.map((contract) => ({ id: contract.id, revision: contract.revision })),
    capabilities: capabilities.map((capability) => ({ id: capability.id, revision: capability.revision })),
    components: [],
  });
  if (!result.ok) {
    throw new Error('The application definition is invalid; see compile diagnostics.');
  }
  return result.plan;
}
