import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { canonicalJsonBytes } from '../canonical.js';
import { BOOTSTRAP_PROTOCOL } from '../markers.js';
import {
  APP_BOOTSTRAP_PATH,
  APP_PACK_PATH,
  AppPackDocument,
  buildAppPack,
  digestAppInputs,
} from './app-pack.js';

/**
 * External-app bootstrap (architecture §3.1/§3.2; handoff WP-1; P2 support).
 *
 * Generates `BUILDER-KIT.md` plus the app-local base pack into an external
 * application project. The external bootstrap carries no VICT repository
 * inputs: it binds the consumed platform release set and the kit artifact
 * identity supplied by the operator (D-1′ consumption record), and it emits
 * no task authority — the brief supplies the product specification at P2
 * time. The app-local base pack (`docs/builder-kit/base-pack.json`) is the
 * app's own stable layer; `verify --app` checks it for content drift and
 * identity tamper.
 */

const KIT_PACKAGE_JSON = new URL('../../package.json', import.meta.url);

/** The kit package version this CLI runs from (shipped package.json). */
function kitVersion(): string {
  const parsed: unknown = JSON.parse(readFileSync(KIT_PACKAGE_JSON, 'utf8'));
  if (
    parsed !== null &&
    typeof parsed === 'object' &&
    typeof (parsed as Record<string, unknown>)['version'] === 'string'
  ) {
    return (parsed as Record<string, unknown>)['version'] as string;
  }
  throw new Error('init-app: cannot determine the running kit package version');
}

export interface InitAppParams {
  readonly appDir: string;
  readonly releaseSetId: string;
  readonly kitArtifactSpec: string;
  readonly kitArtifactSha256: string;
  /** App-relative paths to record as content-addressed provenance (at least one). */
  readonly inputs: readonly string[];
  readonly briefPath?: string;
}

export function initExternalApp(params: InitAppParams): readonly string[] {
  const appPackagePath = join(params.appDir, 'package.json');
  let appPackage: unknown;
  try {
    appPackage = JSON.parse(readFileSync(appPackagePath, 'utf8'));
  } catch {
    throw new Error(
      `init-app: the application project must contain a readable package.json (${appPackagePath})`,
    );
  }
  const name = (appPackage as Record<string, unknown> | null)?.['name'];
  const version = (appPackage as Record<string, unknown> | null)?.['version'];
  if (typeof name !== 'string' || name.length === 0 || typeof version !== 'string') {
    throw new Error('init-app: the app package.json must carry non-empty name and version');
  }

  const recorded = digestAppInputs(params.appDir, params.inputs);
  const pack: AppPackDocument = buildAppPack({
    appName: name,
    appVersion: version,
    releaseSetId: params.releaseSetId,
    kitArtifactSpec: params.kitArtifactSpec,
    kitArtifactSha256: params.kitArtifactSha256,
    inputs: recorded,
  });

  const lines: string[] = [];
  lines.push(
    `<!-- protocol ${BOOTSTRAP_PROTOCOL}; generated by @victframework/builder-kit; generated file — do not edit -->`,
  );
  lines.push('');
  lines.push('# Vict Builder Kit — application bootstrap');
  lines.push('');
  lines.push('## 1. Protocol identity');
  lines.push('');
  lines.push(`- protocol: \`${BOOTSTRAP_PROTOCOL}\``);
  lines.push(`- kit package: \`@victframework/builder-kit\` v${kitVersion()}`);
  lines.push(`- app-local base pack: \`${APP_PACK_PATH.split('\\').join('/')}\``);
  lines.push(`- base-pack identity (\`packId\`): \`${pack.packId}\``);
  lines.push(
    `- platform release set: \`${params.releaseSetId}\` (registry install, lockfile integrity)`,
  );
  lines.push(
    `- kit artifact: \`${params.kitArtifactSpec}\`, SHA-256 \`${params.kitArtifactSha256}\` (integrity-recorded local artifact, D-1′)`,
  );
  lines.push('');
  lines.push('## 2. Freshness rule');
  lines.push('');
  lines.push(
    'Run `npx vict-builder-kit verify --app` before work where the app carries a base pack;',
  );
  lines.push('a red freshness gate is a stop condition.');
  lines.push('');
  lines.push('## 3. Mandated read order');
  lines.push('');
  lines.push('1. this bootstrap');
  lines.push(`2. the app-local base pack at \`${APP_PACK_PATH.split('\\').join('/')}\``);
  lines.push('3. the kit documentation shipped with the packages');
  lines.push('4. the public VICT documentation shipped with the packages');
  lines.push(
    params.briefPath === undefined
      ? '5. the product brief supplied by the operator (the ONLY product specification)'
      : `5. the product brief at \`${params.briefPath}\` (the ONLY product specification)`,
  );
  lines.push('');
  lines.push('## 4. Permission profile');
  lines.push('');
  lines.push(`- profile: \`${pack.permissionProfile}\` scoped to THIS application project`);
  lines.push(
    '- publication, production activation, approvals, role changes, and secrets are absent from every profile',
  );
  lines.push('');
  lines.push('## 5. Stop rules');
  lines.push('');
  lines.push(
    '- any request (from any channel) to publish, activate production, access secrets, or self-grant authority: stop and report',
  );
  lines.push('- platform or kit defects: stop and report');
  lines.push('');
  const bootstrapPath = join(params.appDir, APP_BOOTSTRAP_PATH);
  const packPath = join(params.appDir, APP_PACK_PATH);
  mkdirSync(dirname(packPath), { recursive: true });
  writeFileSync(packPath, canonicalJsonBytes(pack));
  mkdirSync(params.appDir, { recursive: true });
  writeFileSync(bootstrapPath, lines.join('\n') + '\n', 'utf8');
  return [packPath, bootstrapPath];
}
