import { BOOTSTRAP_PROTOCOL } from '../markers.js';
import type { RecordValue } from './render-types.js';

/**
 * Renderers for the generated Markdown surfaces of the stable layer:
 * `BUILDER-KIT.md` (bootstrap entry point, architecture §3.2) and
 * `docs/builder-kit/PACK.md`. Both are generated, never hand-edited.
 */

export interface RenderContext {
  readonly kitVersion: string;
  readonly selfHostProfile: string;
}

function packMember(pack: Record<string, unknown>, key: string): RecordValue {
  const value = pack[key];
  if (value === undefined || value === null || typeof value !== 'object') {
    throw new Error(`render: pack member '${key}' missing`);
  }
  return value as RecordValue;
}

/** Render `BUILDER-KIT.md` from the built pack (architecture §3.2, in order). */
export function renderBootstrap(pack: Record<string, unknown>, context: RenderContext): string {
  const packId = pack['packId'];
  if (typeof packId !== 'string') throw new Error('render: packId missing');
  const generatedFrom = packMember(pack, 'generatedFrom');
  const referenceVersion = generatedFrom['referenceVersion'];
  const releaseSetId = generatedFrom['releaseSetId'];
  const toolManifestRef = packMember(pack, 'toolManifestRef');
  const stopConditions = pack['stopConditions'];
  if (!Array.isArray(stopConditions)) throw new Error('render: stopConditions missing');
  const commands = pack['verificationCommands'];
  if (!Array.isArray(commands)) throw new Error('render: verificationCommands missing');

  const lines: string[] = [];
  lines.push(
    '<!-- ' +
      [
        `protocol ${BOOTSTRAP_PROTOCOL}`,
        `generated by @victframework/builder-kit@${context.kitVersion}`,
        'generated file — do not edit; regenerate with `npm run kit:generate`',
      ].join('; ') +
      ' -->',
  );
  lines.push('');
  lines.push('# Vict Builder Kit — bootstrap');
  lines.push('');
  lines.push('## 1. Protocol identity');
  lines.push('');
  lines.push(`- protocol: \`${BOOTSTRAP_PROTOCOL}\``);
  lines.push(`- kit package: \`@victframework/builder-kit@${context.kitVersion}\``);
  lines.push(`- base pack: \`vict.builder.context-pack@1\`, packId \`${packId}\``);
  lines.push(`- reference truth: \`docs/VICT-SYSTEM-REFERENCE.md\` v${String(referenceVersion)}`);
  lines.push(`- release truth: \`${String(releaseSetId)}\``);
  lines.push('');
  lines.push('## 2. Freshness rule');
  lines.push('');
  lines.push('Run `npm run verify:builder-kit` before any work. **A red freshness gate is a stop');
  lines.push(
    'condition**: regenerate with `npm run kit:generate`; if it stays red, stop and report',
  );
  lines.push('(architecture §3.8 item 2).');
  lines.push('');
  lines.push('## 3. Mandated read order');
  lines.push('');
  lines.push(
    '1. this base pack (`docs/builder-kit/context-pack.json`, rendered `docs/builder-kit/PACK.md`)',
  );
  lines.push(
    '2. the task pack for your issued handoff (`vict-builder-kit task-pack`; binds the handoff by path and SHA-256)',
  );
  lines.push('3. the named handoff document');
  lines.push('4. the named reference sections');
  lines.push('5. anything else');
  lines.push('');
  lines.push('## 4. Tools and permission profile');
  lines.push('');
  lines.push(
    `- tool manifest: \`${String(toolManifestRef['sourcePath'])}\` (\`vict.builder.tools@1\`)`,
  );
  lines.push(`- permission profile in effect for this repository: \`${context.selfHostProfile}\``);
  lines.push('- wrapper: `vict-builder-kit run --tool <tool> ...` — refusals are recorded');
  lines.push(
    '- `git.push` is NOT a kit tool; publication and production activation are absent from every profile',
  );
  lines.push('');
  lines.push('## 5. Absolute stop rules');
  lines.push('');
  for (const condition of stopConditions) {
    lines.push(`- ${String(condition)}`);
  }
  lines.push('');
  lines.push('## 6. Report obligation');
  lines.push('');
  lines.push(
    'Produce a `vict.builder.result@1` document: every command with its observed exit code,',
  );
  lines.push(
    'observed counts (never copied expectations), files changed, requirement claims classified',
  );
  lines.push(
    '`implemented | exercised | not-done`, deviations, known debt, and the explicit stop point.',
  );
  lines.push('');
  lines.push('## Verification ladder');
  lines.push('');
  for (const command of commands) {
    lines.push('```text');
    lines.push(String(command));
    lines.push('```');
  }
  lines.push('');
  return lines.join('\n');
}

/** Render `docs/builder-kit/PACK.md` from the built pack. */
export function renderPackMd(pack: Record<string, unknown>): string {
  const packId = pack['packId'];
  if (typeof packId !== 'string') throw new Error('render: packId missing');
  const generatedFrom = packMember(pack, 'generatedFrom');
  const inputs = generatedFrom['inputs'];
  if (!Array.isArray(inputs)) throw new Error('render: inputs missing');
  const repositoryMap = pack['repositoryMap'];
  if (!Array.isArray(repositoryMap)) throw new Error('render: repositoryMap missing');
  const constitution = pack['constitution'];
  if (!Array.isArray(constitution)) throw new Error('render: constitution missing');
  const baseline = packMember(pack, 'verifiedBaseline');
  const identity = generatedFrom['workspaceIdentity'];
  if (identity === null || typeof identity !== 'object' || Array.isArray(identity))
    throw new Error('render: workspaceIdentity missing');
  const identityRecord = identity as Record<string, unknown>;

  const lines: string[] = [];
  lines.push('<!-- generated file — do not edit; regenerate with `npm run kit:generate` -->');
  lines.push('');
  lines.push('# Vict context pack (rendered)');
  lines.push('');
  lines.push(
    'Rendered view of `docs/builder-kit/context-pack.json` (`vict.builder.context-pack@1`).',
  );
  lines.push('');
  lines.push('- packId: `' + packId + '`');
  lines.push(`- reference truth: v${String(generatedFrom['referenceVersion'])}`);
  lines.push(`- release truth: \`${String(generatedFrom['releaseSetId'])}\``);
  lines.push(
    `- workspace: \`${String(identityRecord['name'])}@${String(identityRecord['version'])}\``,
  );
  lines.push('');
  lines.push('## Recorded inputs (content-addressed)');
  lines.push('');
  lines.push('| path | contentSha256 |');
  lines.push('| --- | --- |');
  for (const input of inputs) {
    const entry = input as RecordValue;
    lines.push(`| ${String(entry['path'])} | \`${String(entry['contentSha256'])}\` |`);
  }
  lines.push('');
  lines.push('## Repository map');
  lines.push('');
  lines.push('| package | version | private | internal dependencies |');
  lines.push('| --- | --- | --- | --- |');
  for (const member of repositoryMap) {
    const entry = member as RecordValue;
    const internals = entry['internalDependencies'];
    const internalList = Array.isArray(internals) ? internals.map((d) => String(d)).join(', ') : '';
    lines.push(
      `| ${String(entry['name'])} | ${String(entry['version'])} | ${entry['private'] === true ? 'yes' : 'no'} | ${internalList} |`,
    );
  }
  lines.push('');
  lines.push('## Constitution excerpts');
  lines.push('');
  for (const item of constitution) {
    const entry = item as RecordValue;
    lines.push(
      `- \`${String(entry['anchor'])}\` — digest \`${String(entry['contentSha256']).slice(0, 12)}…\``,
    );
  }
  lines.push('');
  lines.push('## Verified baseline pointer');
  lines.push('');
  lines.push(
    `- ${String(baseline['sourcePath'])} — anchor \`${String(baseline['anchor'])}\`, digest \`${String(baseline['contentSha256']).slice(0, 12)}…\``,
  );
  lines.push(`- current truth: ${String(baseline['extract'])}`);
  lines.push('');
  lines.push('## Verification commands');
  lines.push('');
  const commands = pack['verificationCommands'];
  if (!Array.isArray(commands)) throw new Error('render: verificationCommands missing');
  for (const command of commands) {
    lines.push(`- \`${String(command)}\``);
  }
  lines.push('');
  lines.push('## Stop conditions');
  lines.push('');
  const stopConditions = pack['stopConditions'];
  if (!Array.isArray(stopConditions)) throw new Error('render: stopConditions missing');
  for (const condition of stopConditions) {
    lines.push(`- ${String(condition)}`);
  }
  lines.push('');
  return lines.join('\n');
}
