import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { generateCatalog, CatalogGenerationError } from '../catalog/generate.js';
import { canonicalJsonBytes, packIdentityFromBytes, sha256Hex } from '../canonical.js';
import {
  buildContextPack,
  contextPackBytes,
  CONTEXT_PACK_PATH,
  CATALOG_PATH,
  PACK_MD_PATH,
  BOOTSTRAP_PATH,
  PROFILES_PATH,
  TOOL_MANIFEST_PATH,
} from '../generate/context-pack.js';
import { renderBootstrap, renderPackMd } from '../generate/render.js';
import {
  discoverWorkspaceManifests,
  readReferenceVersion,
  readReleaseSetId,
  readWorkspaceIdentity,
} from '../inputs.js';
import { CATALOG_SCHEMA, CONTEXT_PACK_SCHEMA, PROFILE_SCHEMA, TOOLS_SCHEMA } from '../markers.js';
import { scanFirstPartySources } from '../catalog/static-scan.js';
import { validateDocument, validateProfile, validateTools } from '../validate/index.js';
import { compareBaseline, loadTaskPack, taskPackRoot } from './baseline.js';

/**
 * `verify:builder-kit` — the freshness/identity/completeness gate
 * (architecture §3.9/§4.3). Regenerates and compares both pack layers,
 * recomputes identities with the §3.3 exclusions, recomputes the catalog
 * from typed declarations (fail-closed), validates schemas, checks all
 * drift classes, plants canary credentials and proves they never reach
 * any generated byte, and — when a task pack is present — compares the
 * working tree against the pinned baseline.
 */

export interface CheckResult {
  readonly id: string;
  readonly ok: boolean;
  readonly driftClass: string | null;
  readonly detail: string;
}

export interface VerifyReport {
  readonly ok: boolean;
  readonly checks: readonly CheckResult[];
}

const CANARY_VALUES: readonly string[] = ['vict-canary-secret-7f3a9', 'vict-canary-token-91bc4'];

function plantCanaries(): Record<string, string> {
  const env: Record<string, string> = {};
  // Deterministic canary values (no randomness: tests stay reproducible).
  env['VICT_BUILDER_KIT_CANARY_SECRET'] = CANARY_VALUES[0] ?? '';
  env['VICT_BUILDER_KIT_CANARY_TOKEN'] = CANARY_VALUES[1] ?? '';
  return env;
}

function scanForCanaries(bytes: Buffer, canaries: Record<string, string>): string | null {
  const text = bytes.toString('utf8');
  for (const value of Object.values(canaries)) {
    if (text.includes(value)) return value;
  }
  return null;
}

function listTaskPacks(repoRoot: string): readonly string[] {
  const root = taskPackRoot(repoRoot);
  let entries;
  try {
    entries = readdirSync(root, { withFileTypes: true });
  } catch {
    return [];
  }
  const packs: string[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const candidate = join(root, entry.name, 'task-pack.json');
    try {
      if (statSync(candidate).isFile()) packs.push(candidate);
    } catch {
      continue;
    }
  }
  return packs.sort();
}

/** Run every gate check against the repository at `repoRoot`. */
export function verifyBuilderKit(repoRoot: string): VerifyReport {
  const checks: CheckResult[] = [];
  const record = (id: string, ok: boolean, driftClass: string | null, detail: string): void => {
    checks.push({ id, ok, driftClass, detail });
  };

  const canaries = plantCanaries();

  // ---- 1. schema validation of the committed stable layer -----------------
  let committedPack: Record<string, unknown> | null = null;
  try {
    const bytes = readFileSync(join(repoRoot, CONTEXT_PACK_PATH));
    committedPack = JSON.parse(bytes.toString('utf8')) as Record<string, unknown>;
    const result = validateDocument(committedPack);
    record(
      'schema:context-pack',
      result.ok,
      result.ok ? null : 'schema-invalid',
      result.ok ? `valid ${CONTEXT_PACK_SCHEMA}` : structuredIssues(result),
    );
  } catch (error) {
    record(
      'schema:context-pack',
      false,
      'schema-invalid',
      `unreadable: ${(error as Error).message}`,
    );
  }

  let committedCatalogBytes: Buffer | null = null;
  try {
    committedCatalogBytes = readFileSync(join(repoRoot, CATALOG_PATH));
    const result = validateDocument(JSON.parse(committedCatalogBytes.toString('utf8')));
    record(
      'schema:catalog',
      result.ok,
      result.ok ? null : 'schema-invalid',
      result.ok ? `valid ${CATALOG_SCHEMA}` : structuredIssues(result),
    );
  } catch (error) {
    record('schema:catalog', false, 'schema-invalid', `unreadable: ${(error as Error).message}`);
  }

  let toolsBytes: Buffer | null = null;
  try {
    toolsBytes = readFileSync(join(repoRoot, TOOL_MANIFEST_PATH));
    const result = validateTools(JSON.parse(toolsBytes.toString('utf8')));
    record(
      'schema:tools',
      result.ok,
      result.ok ? null : 'schema-invalid',
      result.ok ? `valid ${TOOLS_SCHEMA}` : structuredIssues(result),
    );
  } catch (error) {
    record('schema:tools', false, 'schema-invalid', `unreadable: ${(error as Error).message}`);
  }

  let profilesBytes: Buffer | null = null;
  try {
    profilesBytes = readFileSync(join(repoRoot, PROFILES_PATH));
    const parsed: unknown = JSON.parse(profilesBytes.toString('utf8'));
    const profiles = Array.isArray(parsed) ? parsed : [parsed];
    const invalid = profiles.filter((profile) => !validateProfile(profile).ok);
    record(
      'schema:profiles',
      invalid.length === 0,
      invalid.length === 0 ? null : 'schema-invalid',
      invalid.length === 0
        ? `valid ${PROFILE_SCHEMA} × ${String(profiles.length)}`
        : `${String(invalid.length)} invalid profile(s)`,
    );
  } catch (error) {
    record('schema:profiles', false, 'schema-invalid', `unreadable: ${(error as Error).message}`);
  }

  // ---- 2. pack identity (exclusion rule, §3.3/§4.4) ----------------------
  const committedPackBytes = (() => {
    try {
      return readFileSync(join(repoRoot, CONTEXT_PACK_PATH));
    } catch {
      return null;
    }
  })();
  if (committedPackBytes !== null && committedPack !== null) {
    let recomputed: string | null = null;
    try {
      recomputed = packIdentityFromBytes(committedPackBytes);
    } catch (error) {
      record(
        'identity:base-pack',
        false,
        'pack-tamper',
        `identity recomputation failed: ${(error as Error).message}`,
      );
    }
    const recorded = committedPack['packId'];
    if (typeof recorded === 'string' && recomputed !== null) {
      const identityOk = recomputed === recorded;
      // The exclusion rule is normative: the identity must NOT equal the
      // hash over bytes that still contain packId.
      const includingPackId = sha256Hex(canonicalJsonBytes({ ...committedPack }));
      record(
        'identity:base-pack',
        identityOk && includingPackId !== recorded,
        identityOk && includingPackId !== recorded ? null : 'pack-tamper',
        identityOk
          ? `packId matches canonical bytes with packId omitted (and differs from the including-packId hash)`
          : `recorded ${recorded.slice(0, 12)}… ≠ recomputed ${recomputed.slice(0, 12)}…`,
      );
    }
  } else if (committedPackBytes === null) {
    record('identity:base-pack', false, 'pack-tamper', 'committed base pack unreadable');
  }

  // Task pack identities (when present).
  for (const taskPackPath of listTaskPacks(repoRoot)) {
    const bytes = readFileSync(taskPackPath);
    try {
      const parsed = JSON.parse(bytes.toString('utf8')) as Record<string, unknown>;
      const recorded = parsed['packId'];
      const recomputed = packIdentityFromBytes(bytes);
      const ok = typeof recorded === 'string' && recorded === recomputed;
      record(
        `identity:${taskPackPath.replace(/\\/g, '/')}`,
        ok,
        ok ? null : 'pack-tamper',
        ok ? 'task pack identity matches' : 'task pack identity mismatch',
      );
    } catch (error) {
      record(
        `identity:${taskPackPath.replace(/\\/g, '/')}`,
        false,
        'pack-tamper',
        (error as Error).message,
      );
    }
  }

  // ---- 3. catalog: fail-closed static completeness -----------------------
  const scan = scanFirstPartySources(repoRoot);
  record(
    'catalog:static-resolvable',
    scan.unresolved.length === 0,
    scan.unresolved.length === 0 ? null : 'catalog-unresolved',
    scan.unresolved.length === 0
      ? `every first-party declaration resolved statically (${String(scan.declarations.length)} declaration(s))`
      : `unresolvable declaration(s): ${scan.unresolved
          .map((entry) => `${entry.file}: ${entry.reason}`)
          .join('; ')
          .slice(0, 500)}`,
  );

  // ---- 4. catalog: regenerate in the isolated child and compare ----------
  try {
    const { catalog } = generateCatalog(repoRoot, { env: canaries });
    const regeneratedCatalogBytes = canonicalJsonBytes(catalog);
    const catalogMatches =
      committedCatalogBytes !== null && regeneratedCatalogBytes.equals(committedCatalogBytes);
    record(
      'catalog:regenerate-compare',
      catalogMatches,
      catalogMatches ? null : 'catalog-drift',
      catalogMatches
        ? 'regenerated catalog is byte-identical to the committed catalog'
        : 'regenerated catalog differs from the committed catalog',
    );
    // Canary hygiene over the regenerated bytes.
    const leaked = scanForCanaries(regeneratedCatalogBytes, canaries);
    record(
      'canary:catalog',
      leaked === null,
      leaked === null ? null : 'secret-leak',
      leaked === null
        ? 'no canary value in generated catalog bytes'
        : `canary value leaked into catalog bytes`,
    );
  } catch (error) {
    const details =
      error instanceof CatalogGenerationError
        ? error.details.join(' | ')
        : (error as Error).message;
    record(
      'catalog:regenerate-compare',
      false,
      'catalog-drift',
      `catalog generation failed: ${details}`,
    );
    record(
      'canary:catalog',
      false,
      'secret-leak',
      'catalog generation failed; canary scan not possible',
    );
  }

  // ---- 5. catalog: static set === committed catalog set ------------------
  if (committedCatalogBytes !== null) {
    try {
      const committed = JSON.parse(committedCatalogBytes.toString('utf8')) as {
        packs?: { capabilities?: { id?: unknown; revision?: unknown }[] }[];
      };
      const committedSet = new Set<string>();
      for (const pack of committed.packs ?? []) {
        for (const capability of pack.capabilities ?? []) {
          if (typeof capability.id === 'string' && typeof capability.revision === 'string') {
            committedSet.add(`${capability.id}@${capability.revision}`);
          }
        }
      }
      const staticSet = new Set(
        scan.declarations.map((declaration) => `${declaration.id}@${declaration.revision}`),
      );
      const missing = [...staticSet].filter((entry) => !committedSet.has(entry));
      const dangling = [...committedSet].filter((entry) => !staticSet.has(entry));
      const ok = missing.length === 0 && dangling.length === 0;
      record(
        'catalog:completeness',
        ok,
        ok ? null : 'catalog-drift',
        ok
          ? `static declarations equal committed catalog entries (${String(staticSet.size)})`
          : `missing from catalog: ${missing.join(', ') || 'none'}; absent from source: ${dangling.join(', ') || 'none'}`,
      );
    } catch (error) {
      record(
        'catalog:completeness',
        false,
        'catalog-drift',
        `committed catalog unparsable: ${(error as Error).message}`,
      );
    }
  }

  // ---- 6. catalog: dangling references -----------------------------------
  if (committedCatalogBytes !== null) {
    const problems = findDanglingReferences(committedCatalogBytes, repoRoot);
    record(
      'catalog:dangling',
      problems.length === 0,
      problems.length === 0 ? null : 'catalog-dangling',
      problems.length === 0
        ? 'every catalog reference resolves (packages, modules, contract revisions)'
        : problems.join('; ').slice(0, 500),
    );
  }

  // ---- 7. recorded-input drift: regenerate the base pack -----------------
  try {
    const regenerated = buildContextPack(repoRoot);
    const regeneratedBytes = contextPackBytes(regenerated.pack);
    const matches = committedPackBytes !== null && regeneratedBytes.equals(committedPackBytes);
    record(
      'pack:regenerate-compare',
      matches,
      matches ? null : 'content-drift',
      matches
        ? 'regenerated base pack (with BUILDER-KIT.md and PACK.md renderings) is byte-identical to the committed layer'
        : 'regenerated base pack differs from the committed base pack',
    );
    const leaked = scanForCanaries(regeneratedBytes, canaries);
    record(
      'canary:base-pack',
      leaked === null,
      leaked === null ? null : 'secret-leak',
      leaked === null
        ? 'no canary value in generated pack bytes'
        : 'canary value leaked into pack bytes',
    );
    // Renderings are compared unconditionally: a stale BUILDER-KIT.md or
    // PACK.md is drift even when the pack bytes themselves match.
    const bootstrapMatches =
      renderBootstrap(regenerated.pack, {
        kitVersion: kitVersion(repoRoot),
        selfHostProfile: 'builder.selfhost',
      }) === safeRead(join(repoRoot, BOOTSTRAP_PATH));
    const packMdMatches = renderPackMd(regenerated.pack) === safeRead(join(repoRoot, PACK_MD_PATH));
    record(
      'pack:renderings',
      bootstrapMatches && packMdMatches,
      bootstrapMatches && packMdMatches ? null : 'generated-artifact-drift',
      `BUILDER-KIT.md ${bootstrapMatches ? 'current' : 'stale'}; PACK.md ${packMdMatches ? 'current' : 'stale'}`,
    );
  } catch (error) {
    const message = (error as Error).message;
    const driftClass = message.includes('recorded input(s) missing')
      ? 'unregistered-input'
      : 'content-drift';
    record(
      'pack:regenerate-compare',
      false,
      driftClass,
      `base-pack regeneration failed: ${message}`,
    );
  }

  // ---- 8. release identity ----------------------------------------------
  const releaseSetId = readReleaseSetId(repoRoot);
  const recordedRelease =
    committedPack === null ? null : readGeneratedFrom(committedPack, 'releaseSetId');
  if (releaseSetId !== null && typeof recordedRelease === 'string') {
    const ok = releaseSetId === recordedRelease;
    record(
      'identity:release-set',
      ok,
      ok ? null : 'release-identity-drift',
      ok
        ? `release identity ${releaseSetId}`
        : `recorded ${recordedRelease} ≠ current ${releaseSetId}`,
    );
  }

  // ---- 9. workspace identity --------------------------------------------
  const workspaceIdentity = readWorkspaceIdentity(repoRoot);
  const recordedIdentity =
    committedPack === null ? null : readGeneratedFrom(committedPack, 'workspaceIdentity');
  if (
    workspaceIdentity !== null &&
    recordedIdentity !== null &&
    typeof recordedIdentity === 'object'
  ) {
    const recorded = recordedIdentity as Record<string, unknown>;
    const sameRoot =
      recorded['name'] === workspaceIdentity.name &&
      recorded['version'] === workspaceIdentity.version &&
      JSON.stringify(recorded['workspaces']) === JSON.stringify(workspaceIdentity.workspaces);
    const committedMembers = committedPack === null ? [] : committedRepositoryMap(committedPack);
    const currentMembers = discoverWorkspaceManifests(repoRoot)
      .map(({ manifest }) => manifest['name'])
      .filter((name): name is string => typeof name === 'string')
      .filter((name) => name !== workspaceIdentity.name)
      .sort();
    const sameMembers = JSON.stringify(committedMembers) === JSON.stringify(currentMembers);
    record(
      'identity:workspace',
      sameRoot && sameMembers,
      sameRoot && sameMembers ? null : 'workspace-identity-drift',
      sameRoot && sameMembers
        ? `workspace identity current (${String(currentMembers.length)} manifests)`
        : `root identity ${sameRoot ? 'current' : 'changed'}; workspace membership ${sameMembers ? 'current' : 'changed'}`,
    );
  }

  // ---- 10. reference version --------------------------------------------
  const referenceVersion = readReferenceVersion(repoRoot);
  const recordedVersion =
    committedPack === null ? null : readGeneratedFrom(committedPack, 'referenceVersion');
  if (referenceVersion !== null && typeof recordedVersion === 'string') {
    const ok = referenceVersion === recordedVersion;
    record(
      'identity:reference-version',
      ok,
      ok ? null : 'content-drift',
      ok
        ? `reference v${referenceVersion}`
        : `recorded v${recordedVersion} ≠ current v${referenceVersion}`,
    );
  }

  // ---- 11. tool/profile digests recorded in the pack --------------------
  if (committedPack !== null && toolsBytes !== null && profilesBytes !== null) {
    const toolRef = committedPack['toolManifestRef'];
    const profileRef = committedPack['permissionProfilesRef'];
    const toolsDigestOk =
      typeof toolRef === 'object' &&
      toolRef !== null &&
      (toolRef as Record<string, unknown>)['contentSha256'] === sha256Hex(toolsBytes);
    const profilesDigestOk =
      typeof profileRef === 'object' &&
      profileRef !== null &&
      (profileRef as Record<string, unknown>)['contentSha256'] === sha256Hex(profilesBytes);
    const ok = toolsDigestOk && profilesDigestOk;
    record(
      'identity:tools-profiles',
      ok,
      ok ? null : 'content-drift',
      ok
        ? 'tool manifest and profile digests match the pack references'
        : 'tool manifest or profile data changed without regeneration',
    );
  }

  // ---- 12. baseline comparison (when a task pack exists) ----------------
  const taskPacks = listTaskPacks(repoRoot);
  if (taskPacks.length === 0) {
    record(
      'baseline:comparison',
      true,
      null,
      'no task pack present; baseline comparison not applicable',
    );
  } else {
    for (const taskPackPath of taskPacks) {
      const taskPack = loadTaskPack(taskPackPath);
      if (taskPack === null) {
        record(
          `baseline:${taskPackPath.replace(/\\/g, '/')}`,
          false,
          'schema-invalid',
          'task pack unreadable',
        );
        continue;
      }
      const comparison = compareBaseline(
        repoRoot,
        taskPack.baseTree,
        taskPack.inScopePaths,
        taskPack.ignoreManifest,
      );
      if (comparison === null) {
        record(
          `baseline:${taskPackPath.replace(/\\/g, '/')}`,
          false,
          'baseline-escape',
          `git comparison against ${taskPack.baseTree.slice(0, 12)}… failed`,
        );
        continue;
      }
      const ok = comparison.escapes.length === 0;
      record(
        `baseline:${taskPackPath.replace(/\\/g, '/')}`,
        ok,
        ok ? null : 'baseline-escape',
        ok
          ? `all working-tree changes versus ${taskPack.baseTree.slice(0, 12)}… are in scope (${String(comparison.changes.filter((c) => !c.ignored).length)} tracked)`
          : `out-of-scope change(s): ${comparison.escapes
              .map((escape) => `${escape.path} [${escape.changeClass}]`)
              .join(', ')
              .slice(0, 400)}`,
      );
    }
  }

  return { ok: checks.every((check) => check.ok), checks };
}

function structuredIssues(result: {
  readonly ok: false;
  readonly issues: readonly {
    readonly code: string;
    readonly path: string;
    readonly message: string;
  }[];
}): string {
  return result.issues
    .map((entry) => `${entry.code} at ${entry.path}`)
    .join('; ')
    .slice(0, 500);
}

function readGeneratedFrom(pack: Record<string, unknown>, key: string): unknown {
  const generatedFrom = pack['generatedFrom'];
  if (generatedFrom === null || typeof generatedFrom !== 'object') return null;
  return (generatedFrom as Record<string, unknown>)[key];
}

function committedRepositoryMap(pack: Record<string, unknown>): readonly string[] {
  const map = pack['repositoryMap'];
  if (!Array.isArray(map)) return [];
  return map
    .map((entry) =>
      entry !== null && typeof entry === 'object'
        ? (entry as Record<string, unknown>)['name']
        : null,
    )
    .filter((name): name is string => typeof name === 'string')
    .sort();
}

function safeRead(path: string): string {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return '';
  }
}

function kitVersion(repoRoot: string): string {
  const manifest = JSON.parse(
    readFileSync(join(repoRoot, 'packages', 'builder-kit', 'package.json'), 'utf8'),
  ) as Record<string, unknown>;
  const version = manifest['version'];
  if (typeof version !== 'string') throw new Error('kit version not readable');
  return version;
}

/** Catalog references that point at nonexistent packages/modules/contract revisions. */
function findDanglingReferences(catalogBytes: Buffer, repoRoot: string): readonly string[] {
  const problems: string[] = [];
  const catalog = JSON.parse(catalogBytes.toString('utf8')) as {
    packs?: {
      id?: unknown;
      contracts?: { id?: unknown; revision?: unknown }[];
      capabilities?: {
        module?: unknown;
        input?: { contractId?: unknown; revision?: unknown } | null;
        output?: { contractId?: unknown; revision?: unknown } | null;
      }[];
    }[];
  };
  for (const pack of catalog.packs ?? []) {
    const packId = typeof pack.id === 'string' ? pack.id : '(unknown pack)';
    const contracts = new Set<string>();
    for (const contract of pack.contracts ?? []) {
      if (typeof contract.id === 'string' && typeof contract.revision === 'string') {
        contracts.add(`${contract.id}@${contract.revision}`);
      }
    }
    for (const capability of pack.capabilities ?? []) {
      const label = `${packId}:${String(capability.module ?? '(no module)')}`;
      if (typeof capability.module === 'string') {
        try {
          statSync(join(repoRoot, capability.module));
        } catch {
          problems.push(`${label}: declaring module missing`);
        }
      }
      for (const ref of [capability.input, capability.output]) {
        if (ref === null || ref === undefined) continue;
        if (typeof ref.contractId === 'string' && typeof ref.revision === 'string') {
          if (!contracts.has(`${ref.contractId}@${ref.revision}`)) {
            problems.push(
              `${label}: contract ${ref.contractId}@${ref.revision} not in pack contracts`,
            );
          }
        }
      }
    }
  }
  return problems;
}
